### PR TITLE
feat: implement single run page filters

### PR DESCRIPTION
**Pull request by kne42**
#44

Screenshot 2024-03-22 at 3 00 34 PM

### CODE REVIEW

**Comment by kne42** [comment]
live link: https://dev-kira-2.cryoet.dev.si.czi.technology/

**Comment by kev-zunshiwang** [comment]
Hey Kira! Implementation looking good!

I'm using a google doc because it's easier to tag people, insert images and track progress.

Can you cross out the feedback you updated? You can also leave a question/comment in the doc using the comment feature and I can help clarify anything.

Lmk if you have any questions!

Feedback doc here: https://docs.google.com/document/d/1Z-TVRad3S1ZGo-ZBOgVDXk7XT-nGDLorD8iQ0h03aK4/edit?usp=sharing

**Comment by kev-zunshiwang** [comment]
**Should have**
- Update to 0px between all the filter dropdown and the filter tag, I see a 8px margin so the spacing is big.
**- Annotation author dropdown**
  - update to 14px spacing for above the Author ORCID
  - update to xs + l, or 20px spacing above the apply button
- **GO ID dropdown**
  - update to xs + l, or 20px spacing above the apply button

**Comment by kev-zunshiwang** [comment]
Must have - update "Annotated object name" to "Object Name" for the Object name filter.

The rest looks good to me! Thanks for all the updates Kira!!!

**Pull request merged**
