### PR TITLE
chore: remove all mentions of kaggle

### PR DESCRIPTION
**Pull request by kne42**
#771 
Screenshot 2024-06-05 at 1 16 22 PM

### CODE REVIEW

**Comment by kne42** [comment]
preview at https://dev-ml-challenge.cryoet.dev.si.czi.technology/competition

**Comment by Janeece** [comment]
@kne42 Does this review include removing the reference to Kaggle in the competition data section? (i see it in original ticket but not in your screenshots/dev environment)

**Comment by kne42** [comment]
> @kne42 Does this review include removing the reference to Kaggle in the competition data section? (i see it in original ticket but not in your screenshots/dev environment)

good catch, I missed that!

**Comment by junxini** [comment]
@kne42 one other small wording consistency change to match the source of truth copy is:

`Example notebooks for existing models, such as TomoTwin and DeePiCt, are provided to serve as onboarding materials and baseline solutions. These examples include preliminary results to set performance benchmarks for the competition.`

we need to change `DeePiCt  -> DeepFinder`

**Pull request merged**
