### PR TITLE
docs: Fix portal links

### LINKED ISSUE #1111: Update link locations on Portal UI
The Portal UI has many links that point to the FAQ page, but the user must find the relevant question in the list of FAQ questions since we do not have a method to open the FAQ accordions from a link. We have added content to the docsite to address this FAQ questions, and we'd like to point the relevant anchors on docsite pages instead of to the Portal FAQ.

An audit of the Portal links was [completed here](https://docs.google.com/spreadsheets/d/1QEPiDcjGJYWSZXsbRjwHd9aeZjbk_tvv2UQ4DKyMwxk/edit?gid=1603036675#gid=1603036675), which details the current and the desired link locations. Many links can be updated by making a PR on [this file](https://github.com/chanzuckerberg/cryoet-data-portal/blob/427c97db0741a52bfdec572a446b1e346b4c95c9/frontend/packages/data-portal/public/locales/en/translation.json#L298).

### PR DESCRIPTION
**Pull request by melissawm**
Closes #1111

### CODE REVIEW

**Comment by dgmccart** [comment]
Hi @kne42, we'd love your review on this to make sure all the updates were made correctly. Also, regarding the FAQ, we are moving forward with directing users to the Portal documentation site instead of FAQ page on the Portal. Ultimately, the Portal FAQ page will be disabled. I will coordinate with Jun about this.

**Comment by melissawm** [comment]
I'm not sure how to address the failing test, I'm afraid.

**Comment by dgmccart** [comment]
> I'm not sure how to address the failing test, I'm afraid.

@kne42 can you help with this as well?

**Comment by dgmccart** [comment]
@melissawm I asked @kne42 about the failing test and she shared that since you are trying to merge the PR from a fork, you need to set up the E2E_CONFIG environment variable to this value
`{"url": "http://localhost:8080","authorName":"Irene de Teresa Trueba","authorOrcId":"0000-0002-4691-9501","runId": "138"}`

**Pull request closed without merging**
