### PR TITLE
fix single dataset visual bugs

### LINKED ISSUE #249: [staging] Some labels in Dataset section in right panel for Single Run page are not per design
**Steps to Reproduce**
1. Open a Run single page
2. Click on "More Info" link or button
3. Open Dataset section
4. Pay attention to "Last Modified", "Authors" and "Affiliation Name"

**Actual Results**
It reads "Last Modified", "Authors" and "Affiliation Name"

**Expected Results**
It should be "Last Modified Date", "Author(s)" and "Affiliation Names"

**Design**
https://www.figma.com/file/AELEVptBVyqp0vvFrzgfK6/4---Single-Run?type=design&node-id=33-69033&mode=design&t=gkw21C24JTsEOTlK-0

**Evidence**

image

### PR DESCRIPTION
**Pull request by kne42**
fixes #249, #244, #150

preview @ https://dev-kira-1.cryoet.dev.si.czi.technology/

### CODE REVIEW

**Comment by Janeece** [comment]
@kne42 thanks for tagging me. Here's my review comments, lmk if you have questions or need more info - 

#224 Feedback:
- looks good, no comments!

#249 Feedback:
- [ ] "Author(s)" still displaying as "Authors"
- [ ] Affiliation row should be removed (not sure if this is part of that ticket, or if there is a separate ticket— its mentioned in the comments)

#150 Feedback:
- [ ] Links have been added to some datasets but not others. Examples:
   - [this dataset](https://dev-kira-1.cryoet.dev.si.czi.technology/datasets/10005?prev=%2Fbrowse-data%2Fdatasets&metadata=dataset&tab=metadata) has links for cellular component but not organism or cell line
   - [this dataset](https://dev-kira-1.cryoet.dev.si.czi.technology/datasets/10000?prev=%2Fbrowse-data%2Fdatasets&metadata=dataset&tab=metadata) has links for organism & cell line (none missing for available metadata)
- [ ] Sometimes link seems to go to generic search page, not the entry for that line/strain
- [ ] links available on the dataset info panel are not showing up on run page info panel (should be same)

**Comment by kne42** [comment]
> * [ ]  "Author(s)" still displaying as "Authors"

This automatically changes between "Author" and "Authors" depending on how many authors are present as I brought up as an idea in a meeting, do you still prefer "Author(s)"?

> * [ ]  Links have been added to some datasets but not others. Examples:
>   
>   * [this dataset](https://dev-kira-1.cryoet.dev.si.czi.technology/datasets/10005?prev=%2Fbrowse-data%2Fdatasets&metadata=dataset&tab=metadata) has links for cellular component but not organism or cell line
>   * [this dataset](https://dev-kira-1.cryoet.dev.si.czi.technology/datasets/10000?prev=%2Fbrowse-data%2Fdatasets&metadata=dataset&tab=metadata) has links for organism & cell line (none missing for available metadata)

This is because we rely on separate fields in the database regarding the IDs of each organism/cell and sometimes the name is provided but not the ID. I'll double check to make sure but this might be an issue stemming from what data is populated.

> * [ ]  Sometimes link seems to go to generic search page, not the entry for that line/strain

Could you give some specific examples so I can debug better please?

> * [ ]  links available on the dataset info panel are not showing up on run page info panel (should be same)

Good catch! I forgot to fetch the data on the run pages 😅

**Comment by Janeece** [comment]
@kne42 All of your replies make sense to me. The author/authors thing is great, i wasn't expecting us to be that fancy! No need to change it, I'll update the design masterfiles. 

>  > - [ ] Sometimes link seems to go to generic search page, not the entry for that line/strain

> Could you give some specific examples so I can debug better please?

An example I found was in [dataset 10004](https://dev-kira-1.cryoet.dev.si.czi.technology/datasets/10004?prev=%2Fbrowse-data%2Fdatasets&metadata=dataset&tab=metadata), the cell line or Strain name (NK2476) links to [this page](https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id=https://cgc.umn.edu/strain/NK2476) -- which appears to be a generic search/root page — idk if its actually a bug.

**Comment by kne42** [comment]
this appears to be because the ID we were given is actually a URL to a completely different site (`https://cgc.umn.edu/strain/NK2476`). @uermel do we want to allow this and link to the site directly or just let it fail as is? linking to the provided site does pose potential security risks tho

I've also just confirmed with @manasaV3 that some fields have their names but no id so some entries not having links is working as intended

**Comment by uermel** [comment]
Defining strains is difficult as there is no all-encompassing database or ontology of strains. The best resources to address this are model organism specific databases and strain collections, which usually maintain ontologies or lists of common strains and curate them. 

Can we whitelist urls to these hosts for the strain ID metadata field, when it is not using TaxID? I've included more collections and databases than we currently have organisms of on the portal to remain future proof.

* Saccharomyces Genome Database: https://www.yeastgenome.org/
* S. Pombe Database: https://www.pombase.org/
* Xenopus Database: https://www.xenbase.org/
* Mouse Strain Ressource: https://www.findmice.org/index
* Rat Genome Database: https://rgd.mcw.edu/
* Nematode Database: https://wormbase.org/
* Dictyostelium Database: http://dictybase.org/
* Allen Institute Cell catalog: https://www.allencell.org/cell-catalog.html
* BacDive: https://bacdive.dsmz.de/

This may be blocked by the question whether an entry is a TaxID or a URL. In order to decide that we could either make these two different metadata fields or keep it in one.

**Comment by kne42** [comment]
given that additional requirement-setting needs to be done, are we okay merging this as-is?

cc @codemonkey800

**Comment by manasaV3** [comment]
Can we open a new issue to track this before we merge this PR?

**Review by Janeece — APPROVED** [review]

**Pull request merged**
